language: objective-c
osx_image: xcode10.2
before_install: scripts/install_deps.sh
script: scripts/build.sh
env:
  global:
    secure: mz2fk26fqCtHzOuu3qQMEuva3HWKLlko48lUW+H3OuB2AQqtqwE2Nn4I4NDbcL1y/zm8pbh/wwwEesDolkR6DIesJUHPSL2dcdyRb5RZ1Em+K/GN2UJYHEk4coeJGgm/aFp9vSUX3nuwjtoDjyU9XcTHnVfGHDNP2vzbTt79eFc=
